// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS2qC3fx5TZEAbd6I4ddYncJqcA8JkryM',
    appId: '1:88533224310:web:e39bf40dccf2250309c857',
    messagingSenderId: '88533224310',
    projectId: 'fashion-c377b',
    authDomain: 'fashion-c377b.firebaseapp.com',
    storageBucket: 'fashion-c377b.appspot.com',
    measurementId: 'G-WKDHQ75X63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC4ku7E-2woIFcTrBe7cPU2GOyC7me2ls',
    appId: '1:88533224310:android:85819424bddd158c09c857',
    messagingSenderId: '88533224310',
    projectId: 'fashion-c377b',
    storageBucket: 'fashion-c377b.appspot.com',
  );
}
